# Generated by Django 3.0.5 on 2020-05-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='human',
            table='Human',
        ),
    ]
